# Generated by Django 4.2.7 on 2025-05-31 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProxmoxHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "host",
                    models.CharField(
                        help_text="IP address or hostname", max_length=255
                    ),
                ),
                ("port", models.IntegerField(default=8006)),
                ("user", models.CharField(default="root@pam", max_length=100)),
                ("verify_ssl", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_connected", models.BooleanField(default=False)),
                ("last_connected", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProxmoxNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("status", models.CharField(default="unknown", max_length=20)),
                ("uptime", models.BigIntegerField(default=0)),
                ("cpu_usage", models.FloatField(default=0.0)),
                ("memory_total", models.BigIntegerField(default=0)),
                ("memory_used", models.BigIntegerField(default=0)),
                ("storage_total", models.BigIntegerField(default=0)),
                ("storage_used", models.BigIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "proxmox_host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="proxmox_integration.proxmoxhost",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("proxmox_host", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProxmoxTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upid", models.CharField(max_length=255, unique=True)),
                ("task_type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("ok", "OK"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("exitstatus", models.CharField(blank=True, max_length=10)),
                ("starttime", models.DateTimeField()),
                ("endtime", models.DateTimeField(blank=True, null=True)),
                ("duration", models.IntegerField(default=0)),
                ("user", models.CharField(blank=True, max_length=100)),
                (
                    "proxmox_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="proxmox_integration.proxmoxnode",
                    ),
                ),
            ],
            options={
                "ordering": ["-starttime"],
            },
        ),
        migrations.CreateModel(
            name="ProxmoxStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storage_id", models.CharField(max_length=100)),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("dir", "Directory"),
                            ("lvm", "LVM"),
                            ("lvmthin", "LVM-Thin"),
                            ("zfs", "ZFS"),
                            ("nfs", "NFS"),
                            ("cifs", "CIFS"),
                            ("glusterfs", "GlusterFS"),
                            ("cephfs", "CephFS"),
                            ("rbd", "RBD"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_types",
                    models.TextField(
                        default="[]", help_text="JSON list of content types"
                    ),
                ),
                ("total_space", models.BigIntegerField(default=0)),
                ("used_space", models.BigIntegerField(default=0)),
                ("available_space", models.BigIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("shared", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "proxmox_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage",
                        to="proxmox_integration.proxmoxnode",
                    ),
                ),
            ],
            options={
                "ordering": ["storage_id"],
                "unique_together": {("proxmox_node", "storage_id")},
            },
        ),
        migrations.CreateModel(
            name="ProxmoxContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vmid", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("hostname", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("suspended", "Suspended"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("template", models.CharField(blank=True, max_length=100)),
                ("cores", models.IntegerField(default=1)),
                ("memory", models.BigIntegerField(default=512)),
                ("swap", models.BigIntegerField(default=0)),
                ("disk_size", models.BigIntegerField(default=0)),
                ("uptime", models.BigIntegerField(default=0)),
                ("cpu_usage", models.FloatField(default=0.0)),
                ("memory_usage", models.BigIntegerField(default=0)),
                (
                    "is_moxnas",
                    models.BooleanField(
                        default=False, help_text="Is this a MoxNAS container?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "proxmox_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="containers",
                        to="proxmox_integration.proxmoxnode",
                    ),
                ),
            ],
            options={
                "ordering": ["vmid"],
                "unique_together": {("proxmox_node", "vmid")},
            },
        ),
    ]
