baseURL: "/"
languageCode: "en-us"
title: "MoxNAS"
theme: "moxnas-theme"

params:
  version: "1.0.0"
  description: "TrueNAS-like NAS Management"
  author: "MoxNAS Team"

menu:
  main:
    - name: "Dashboard"
      url: "/"
      weight: 10
      icon: "dashboard"
    - name: "Storage"
      url: "/storage/"
      weight: 20
      icon: "storage"
    - name: "Shares"
      url: "/shares/"
      weight: 30
      icon: "folder-shared"
    - name: "Network"
      url: "/network/"
      weight: 40
      icon: "network"
    - name: "System"
      url: "/system/"
      weight: 50
      icon: "settings"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: "github"
    lineNos: true

outputs:
  home: ["HTML", "JSON"]
  page: ["HTML"]

security:
  exec:
    allow: ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$"]