# Generated by Django 4.2.7 on 2025-06-25 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProxmoxNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField(default=8006)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("realm", models.CharField(default="pam", max_length=50)),
                ("ssl_verify", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LXCContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vmid", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stopped", "Stopped"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("memory", models.IntegerField(default=2048)),
                ("disk_size", models.IntegerField(default=8)),
                ("cores", models.IntegerField(default=2)),
                (
                    "template",
                    models.CharField(default="ubuntu-22.04-standard", max_length=255),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proxmox.proxmoxnode",
                    ),
                ),
            ],
            options={
                "ordering": ["vmid"],
            },
        ),
    ]
