# Generated by Django 4.2.7 on 2025-05-31 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SNMPConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("contact", models.CharField(blank=True, max_length=200)),
                ("community", models.CharField(default="public", max_length=100)),
                ("v3_enabled", models.BooleanField(default=False)),
                ("v3_username", models.CharField(blank=True, max_length=100)),
                ("v3_auth_type", models.CharField(default="MD5", max_length=20)),
                ("v3_privacy_type", models.CharField(default="AES", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("rsync", "Rsync"),
                            ("cloud", "Cloud Sync"),
                            ("replication", "Replication"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_path", models.CharField(max_length=500)),
                ("destination_path", models.CharField(max_length=500)),
                ("schedule", models.CharField(blank=True, max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("options", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=50)),
                ("uptime", models.BigIntegerField(default=0)),
                ("cpu_usage", models.FloatField(default=0.0)),
                ("memory_total", models.BigIntegerField(default=0)),
                ("memory_used", models.BigIntegerField(default=0)),
                ("load_average", models.TextField(default="0.0,0.0,0.0")),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("failed", "Failed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("memory_usage", models.BigIntegerField(default=0)),
                ("cpu_usage", models.FloatField(default=0.0)),
                ("last_checked", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="UPSConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("driver", models.CharField(blank=True, max_length=100)),
                ("port", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("standalone", "Standalone"),
                            ("netserver", "Network Server"),
                            ("netclient", "Network Client"),
                        ],
                        default="standalone",
                        max_length=20,
                    ),
                ),
                ("shutdown_mode", models.CharField(default="ups_loss", max_length=50)),
                ("shutdown_timer", models.IntegerField(default=30)),
                ("email_notify", models.BooleanField(default=False)),
                ("email_subject", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CronJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("command", models.TextField()),
                ("schedule", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
