# Generated by Django 4.2.7 on 2025-06-24 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Dataset name can only contain letters, numbers, underscores, and hyphens",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                ("path", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True)),
                ("compression", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MountPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=512, unique=True)),
                ("source", models.CharField(max_length=512)),
                ("filesystem", models.CharField(default="ext4", max_length=50)),
                ("options", models.CharField(default="defaults", max_length=255)),
                ("auto_mount", models.BooleanField(default=True)),
                ("mounted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("path", models.CharField(max_length=512)),
                (
                    "protocol",
                    models.CharField(
                        choices=[("smb", "SMB/CIFS"), ("nfs", "NFS"), ("ftp", "FTP")],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("read_only", models.BooleanField(default=False)),
                ("guest_ok", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("smb_browseable", models.BooleanField(default=True)),
                ("smb_writable", models.BooleanField(default=True)),
                ("nfs_readonly", models.BooleanField(default=False)),
                ("nfs_sync", models.BooleanField(default=True)),
                ("nfs_subtree_check", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
