# Generated by Django 4.2.7 on 2025-07-03 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("smb", "SMB/CIFS"),
                            ("nfs", "NFS"),
                            ("ftp", "FTP"),
                            ("ssh", "SSH"),
                            ("snmp", "SNMP"),
                            ("iscsi", "iSCSI"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("port", models.IntegerField()),
                ("config_data", models.JSONField(blank=True, default=dict)),
                ("auto_start", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("cloud_sync", "Cloud Sync"), ("rsync", "Rsync")],
                        max_length=20,
                    ),
                ),
                ("task_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("log_output", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("files_transferred", models.IntegerField(default=0)),
                ("bytes_transferred", models.BigIntegerField(default=0)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UPSConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "ups_type",
                    models.CharField(
                        choices=[
                            ("usb", "USB"),
                            ("serial", "Serial"),
                            ("network", "Network"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "device_path",
                    models.CharField(
                        blank=True, help_text="For USB/Serial UPS", max_length=255
                    ),
                ),
                (
                    "network_host",
                    models.CharField(
                        blank=True, help_text="For Network UPS", max_length=255
                    ),
                ),
                ("network_port", models.IntegerField(blank=True, default=3493)),
                ("driver", models.CharField(default="usbhid-ups", max_length=100)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "shutdown_command",
                    models.CharField(default="shutdown -h now", max_length=255),
                ),
                (
                    "low_battery_runtime",
                    models.IntegerField(
                        default=300, help_text="Seconds before shutdown"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RsyncTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("source_path", models.CharField(max_length=512)),
                ("destination_path", models.CharField(max_length=512)),
                ("remote_host", models.CharField(blank=True, max_length=255)),
                ("remote_user", models.CharField(blank=True, max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("push", "Push to Remote"),
                            ("pull", "Pull from Remote"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("hourly", "Every Hour"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("manual", "Manual Only"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("preserve_permissions", models.BooleanField(default=True)),
                ("preserve_timestamps", models.BooleanField(default=True)),
                ("compress", models.BooleanField(default=False)),
                ("delete_destination", models.BooleanField(default=False)),
                (
                    "exclude_patterns",
                    models.TextField(blank=True, help_text="One pattern per line"),
                ),
                (
                    "rsync_options",
                    models.CharField(
                        blank=True, help_text="Additional rsync options", max_length=255
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(default="never_run", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CloudSyncTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("aws_s3", "Amazon S3"),
                            ("azure_blob", "Azure Blob Storage"),
                            ("google_drive", "Google Drive"),
                            ("dropbox", "Dropbox"),
                            ("backblaze_b2", "Backblaze B2"),
                            ("ftp", "FTP Server"),
                            ("sftp", "SFTP Server"),
                        ],
                        max_length=50,
                    ),
                ),
                ("local_path", models.CharField(max_length=512)),
                ("remote_path", models.CharField(max_length=512)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("push", "Push to Cloud"),
                            ("pull", "Pull from Cloud"),
                            ("sync", "Bidirectional Sync"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("hourly", "Every Hour"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("manual", "Manual Only"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("credentials", models.JSONField(blank=True, default=dict)),
                (
                    "exclude_patterns",
                    models.TextField(blank=True, help_text="One pattern per line"),
                ),
                ("compression", models.BooleanField(default=False)),
                ("encryption", models.BooleanField(default=False)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(default="never_run", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
