# Generated by Django 4.2.7 on 2025-08-17 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        help_text="Device path (e.g., /dev/sda)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human readable name", max_length=255),
                ),
                ("size", models.BigIntegerField(help_text="Size in bytes")),
                (
                    "filesystem",
                    models.CharField(
                        blank=True, help_text="Filesystem type", max_length=50
                    ),
                ),
                (
                    "mount_point",
                    models.CharField(
                        blank=True, help_text="Current mount point", max_length=255
                    ),
                ),
                ("is_mounted", models.BooleanField(default=False)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System disk (not for storage)"
                    ),
                ),
                ("is_removable", models.BooleanField(default=False)),
                ("model", models.CharField(blank=True, max_length=255)),
                ("serial", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MountPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Mount point path", max_length=255, unique=True
                    ),
                ),
                ("filesystem", models.CharField(default="ext4", max_length=50)),
                (
                    "options",
                    models.TextField(default="defaults", help_text="Mount options"),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "auto_mount",
                    models.BooleanField(
                        default=True, help_text="Mount automatically at boot"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "disk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mount_points",
                        to="storage.disk",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="StoragePool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mount_points",
                    models.ManyToManyField(
                        blank=True, related_name="pools", to="storage.mountpoint"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
