# Generated by Django 4.2.7 on 2025-05-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FTPSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("port", models.IntegerField(default=21)),
                ("max_clients", models.IntegerField(default=50)),
                ("max_per_ip", models.IntegerField(default=5)),
                ("max_login_fail", models.IntegerField(default=3)),
                ("timeout", models.IntegerField(default=600)),
                ("anonymous_access", models.BooleanField(default=False)),
                ("local_user_access", models.BooleanField(default=True)),
                ("passive_ports_min", models.IntegerField(default=20000)),
                ("passive_ports_max", models.IntegerField(default=25000)),
                ("tls_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NetworkInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("interface_type", models.CharField(default="ethernet", max_length=20)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("netmask", models.CharField(blank=True, max_length=15)),
                ("gateway", models.GenericIPAddressField(blank=True, null=True)),
                ("dns_servers", models.TextField(blank=True)),
                ("dhcp_enabled", models.BooleanField(default=True)),
                ("enabled", models.BooleanField(default=True)),
                ("mtu", models.IntegerField(default=1500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NFSSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nfs_v3_enabled", models.BooleanField(default=True)),
                ("nfs_v4_enabled", models.BooleanField(default=True)),
                ("rpc_mountd_port", models.IntegerField(default=20048)),
                ("rpc_statd_port", models.IntegerField(default=20049)),
                ("rpc_lockd_port", models.IntegerField(default=20050)),
                ("enable_udp", models.BooleanField(default=True)),
                ("servers", models.IntegerField(default=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SambaSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workgroup", models.CharField(default="WORKGROUP", max_length=50)),
                (
                    "server_string",
                    models.CharField(default="MoxNAS Server", max_length=100),
                ),
                ("netbios_name", models.CharField(default="MOXNAS", max_length=15)),
                ("security", models.CharField(default="user", max_length=20)),
                ("guest_account", models.CharField(default="nobody", max_length=50)),
                ("map_to_guest", models.CharField(default="Bad User", max_length=20)),
                ("enable_recycle_bin", models.BooleanField(default=True)),
                ("audit_enable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SSHSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("port", models.IntegerField(default=22)),
                ("permit_root_login", models.BooleanField(default=False)),
                ("password_authentication", models.BooleanField(default=True)),
                ("pubkey_authentication", models.BooleanField(default=True)),
                ("x11_forwarding", models.BooleanField(default=False)),
                ("max_auth_tries", models.IntegerField(default=3)),
                ("client_alive_interval", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
